### ISSUE TITLE
Update to use with more recent Dakota versions

### ISSUE THREAD

**Issue by verveerpj** [equinor/Carolina#29]
Recent versions of Dakota do not work well with Carolina, because they require a more recent version of boost, which is not compatible anymore with Carolina. This is just an issue of using different boost libraries.

There is now a patch in the Carolina repository that can be applied with `git apply` to fix the setup file to work with recent versions of Dakota.

To make usage of Carolina straightforward again, these changes should be integrated into the setup.py, without affecting usage with older versions of Dakota.

**Comment by andreas-el** [comment]
Resolved through referenced issues.
